{% set name = "tinyrpc" %}
{% set version = "1.0.4" %}
{% set sha256 = "4b41fab967fb1c978f573bf0d609a3b12cc3b6ed62bd3108f43f575563746396" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - six
  run:
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - tinyrpc
    - tinyrpc.dispatch
    - tinyrpc.protocols
    - tinyrpc.server
    - tinyrpc.transports

about:
  home: http://github.com/mbr/tinyrpc
  license: MIT
  license_file: LICENSE
  summary: 'A small, modular, transport and protocol neutral RPC library that, among other things, supports JSON-RPC and zmq.'
  license_family: MIT
  # license_file: LICENSE # https://github.com/mbr/tinyrpc/pull/44
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

extra:
  recipe-maintainers:
    - mariusvniekerk
